In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

### Load the dataset and preview

In [2]:
data = pd.read_csv(r'C:\Users\user\Documents\Applied Machine learning\Percept1.csv', sep=";", header=None)

In [3]:
data, data.columns, data.info(), data.describe()

<class 'pandas.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       99 non-null     float64
 1   1       99 non-null     float64
 2   2       99 non-null     int64
dtypes: float64(2), int64(1)
memory usage: 2.4 KB

(       0     1  2
 0   6.18 -6.92  1
 1  -8.80 -7.34  0
 2   0.71  5.67  1
 3  -4.68  6.93  0
 4   2.21 -9.48  0
 ..   ...   ... ..
 94  6.27  4.49  1
 95  5.70 -8.72  1
 96  9.05 -8.63  1
 97 -2.33 -1.12  0
 98 -5.53  9.23  0

 [99 rows x 3 columns],
 Index([0, 1, 2], dtype='int64'),
 None,
                0          1          2
 count  99.000000  99.000000  99.000000
 mean    0.517172  -0.707677   0.404040
 std     5.931763   5.930600   0.493203
 min    -9.980000  -9.940000   0.000000
 25%    -4.985000  -5.715000   0.000000
 50%     1.310000  -1.040000   0.000000
 75%     5.730000   4.550000   1.000000
 max     9.940000   9.850000   1.000000)

In [4]:
X1 = data.iloc[:, 0:2]
print(X1)

       0     1
0   6.18 -6.92
1  -8.80 -7.34
2   0.71  5.67
3  -4.68  6.93
4   2.21 -9.48
..   ...   ...
94  6.27  4.49
95  5.70 -8.72
96  9.05 -8.63
97 -2.33 -1.12
98 -5.53  9.23

[99 rows x 2 columns]

### MinMax Normalization

In [5]:
scaleMinMax = MinMaxScaler()
# (x- min) / (max - min)
X1_scaled = scaleMinMax.fit_transform(X1)
X1_scaled = pd.DataFrame(X1_scaled, columns=X1.columns)
print(X1_scaled)

           0         1
0   0.811245  0.152602
1   0.059237  0.131379
2   0.536647  0.788782
3   0.266064  0.852451
4   0.611948  0.023244
..       ...       ...
94  0.815763  0.729156
95  0.787149  0.061647
96  0.955321  0.066195
97  0.384036  0.445680
98  0.223394  0.968671

[99 rows x 2 columns]

In [6]:
X1_scaled.describe()

               0          1
count  99.000000  99.000000
mean    0.526966   0.466515
std     0.297779   0.299677
min     0.000000   0.000000
25%     0.250753   0.213492
50%     0.566767   0.449722
75%     0.788655   0.732188
max     1.000000   1.000000

In [7]:
y = data.iloc[:, 2]
print(y)

0     1
1     0
2     1
3     0
4     0
     ..
94    1
95    1
96    1
97    0
98    0
Name: 2, Length: 99, dtype: int64

### Splitting the dataset into training and testing sets

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X1_scaled, y, test_size=0.2, random_state=42)

In [9]:
X_train.describe()

               0          1
count  79.000000  79.000000
mean    0.528958   0.470913
std     0.290630   0.292256
min     0.001004   0.000000
25%     0.250753   0.231935
50%     0.566767   0.452754
75%     0.773594   0.732188
max     1.000000   1.000000

In [10]:
X_test.describe()

               0          1
count  20.000000  20.000000
mean    0.519101   0.449141
std     0.332456   0.334912
min     0.000000   0.004548
25%     0.282129   0.148939
50%     0.543424   0.397928
75%     0.792922   0.688353
max     0.974900   0.959576

### Create perceptron model

In [11]:
model = Perceptron()

In [20]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

### Evalution

In [19]:
accuracy = accuracy_score(y_test, y_pred)

print("Prediction", y_pred)
print("Accuracy", accuracy)

Prediction [0 1 1 0 0 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0]
Accuracy 1.0